export enum Statut {
  EN_ATTENTE_VALIDATION = 'EN_ATTENTE_VALIDATION',
  VALIDE = 'VALIDE',
  REJETE = 'REJETE',
  EN_COURS = 'EN_COURS',
  CLOTURE = 'CLOTURE'
}

export enum RoleUtilisateur {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CHEF_DEPARTEMENT_DOSSIER = 'CHEF_DEPARTEMENT_DOSSIER',
  CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE = 'CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE',
  CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE = 'CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE',
  CHEF_DEPARTEMENT_FINANCE = 'CHEF_DEPARTEMENT_FINANCE',
  AGENT_DOSSIER = 'AGENT_DOSSIER',
  AGENT_RECOUVREMENT_AMIABLE = 'AGENT_RECOUVREMENT_AMIABLE',
  AGENT_RECOUVREMENT_JURIDIQUE = 'AGENT_RECOUVREMENT_JURIDIQUE',
  AGENT_FINANCE = 'AGENT_FINANCE'
}


