export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CHEF_DEPARTEMENT_DOSSIER = 'CHEF_DEPARTEMENT_DOSSIER',
  CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE = 'CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE',
  CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE = 'CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE',
  CHEF_DEPARTEMENT_FINANCE = 'CHEF_DEPARTEMENT_FINANCE',
  AGENT_DOSSIER = 'AGENT_DOSSIER',
  AGENT_RECOUVREMENT_AMIABLE = 'AGENT_RECOUVREMENT_AMIABLE',
  AGENT_RECOUVREMENT_JURIDIQUE = 'AGENT_RECOUVREMENT_JURIDIQUE',
  AGENT_FINANCE = 'AGENT_FINANCE',
}

export enum StatutDossier {
  EN_COURS = 'EN_COURS',
  ENQUETE = 'ENQUETE',
  CLOTURE = 'CLOTURE',
  ARCHIVE = 'ARCHIVE',
}

export enum Urgence {
  FAIBLE = 'FAIBLE',
  MOYENNE = 'MOYENNE',
  ELEVE = 'ELEVE',
}

export enum TypeAction {
  APPEL_TELEPHONIQUE = 'APPEL_TELEPHONIQUE',
  COURRIER = 'COURRIER',
  VISITE = 'VISITE',
  MISE_EN_DEMEURE = 'MISE_EN_DEMEURE',
  ASSIGNATION = 'ASSIGNATION',
  JUGEMENT = 'JUGEMENT',
}

export enum TribunalType {
  PREMIERE_INSTANCE = 'PREMIERE_INSTANCE',
  APPEL = 'APPEL',
  CASSATION = 'CASSATION',
}
