export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CHEF_DEPARTEMENT_DOSSIER = 'CHEF_DEPARTEMENT_DOSSIER',
  CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE = 'CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE',
  CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE = 'CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE',
  CHEF_DEPARTEMENT_FINANCE = 'CHEF_DEPARTEMENT_FINANCE',
  AGENT_DOSSIER = 'AGENT_DOSSIER',
  AGENT_RECOUVREMENT_AMIABLE = 'AGENT_RECOUVREMENT_AMIABLE',
  AGENT_RECOUVREMENT_JURIDIQUE = 'AGENT_RECOUVREMENT_JURIDIQUE',
  AGENT_FINANCE = 'AGENT_FINANCE',
}

// Aligner avec le backend: Statut
export enum StatutDossier {
  EN_ATTENTE_VALIDATION = 'EN_ATTENTE_VALIDATION',
  VALIDE = 'VALIDE',
  REJETE = 'REJETE',
  EN_COURS = 'EN_COURS',
  CLOTURE = 'CLOTURE',
}

export enum Urgence {
  FAIBLE = 'FAIBLE',
  MOYENNE = 'MOYENNE',
  ELEVE = 'ELEVE',
}

// Statut fonctionnel (validation/avancement) aligné sur le backend 'Statut'
export enum ValidationStatut {
  EN_ATTENTE_VALIDATION = 'EN_ATTENTE_VALIDATION',
  VALIDE = 'VALIDE',
  REJETE = 'REJETE',
  EN_COURS = 'EN_COURS',
  CLOTURE = 'CLOTURE',
}

export enum TypeAction {
  APPEL = 'APPEL',
  EMAIL = 'EMAIL',
  VISITE = 'VISITE',
  LETTRE = 'LETTRE',
  AUTRE = 'AUTRE',
  APPEL_TELEPHONIQUE = 'APPEL_TELEPHONIQUE',
  COURRIER = 'COURRIER',
  MISE_EN_DEMEURE = 'MISE_EN_DEMEURE',
  ASSIGNATION = 'ASSIGNATION',
  JUGEMENT = 'JUGEMENT',
}

export enum ReponseDebiteur {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  EN_ATTENTE = 'EN_ATTENTE'
}

export enum StatutTache {
  EN_ATTENTE = 'EN_ATTENTE',
  EN_COURS = 'EN_COURS',
  TERMINEE = 'TERMINEE',
  ANNULEE = 'ANNULEE'
}

export enum TribunalType {
  PREMIERE_INSTANCE = 'PREMIERE_INSTANCE',
  APPEL = 'APPEL',
  CASSATION = 'CASSATION',
}
